### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by AvivLander** [fuwaneko/loopback-connector-rethinkdb#1]
Hi,

Is this something that is functional? I see that there was an initial commit 16 days ago. Is there an NPM for this solution?

Best,
Alexander

**Comment by fuwaneko** [comment]
You can try to use it from GitHub master (i.e. set package.json dependency to this repo instead of version). It **may** work, but many tests are not passing, mainly because of incompatibilities in RDB behavior compared to MongoDB with which I believe tests were written in mind.

**Comment by AvivLander** [comment]
ok thank you, @fuwaneko
