### ISSUE TITLE
loopback rethinkdb connector does not handle explicit property ID

### ISSUE THREAD

**Issue by albhardy** [fuwaneko/loopback-connector-rethinkdb#11]
Hi,
I attempted to use explicit ID for my strongloop model as following:

```
{
  "myId": {
    "type": "string", 
    "id": true 
   }
}
```

When I POST a new record using loopback API explorer (localhost:3000/explorer) - the connector saves the generated guid under default "id" column. As a result, I'm unable to retrieve back the record created  using `GET /Models/{id} - Find a model instance by id from the data source` because StrongLoop expect to search using `myId` column, while rethinkDB still stores the record using default `id` column. 

To resolve this, I need to recreate the RethinkDB Table with predefined index using `r.db('test').tableCreate('myTable', {primaryKey: 'myId'})`. However, the id generated is now no longer returned as response. 

I suspect it should be `if (m.changes && m.changes.length > 0) id = m.generated_keys[0]` instead of `if (m.changes && m.changes.length > 0) id = m.changes[0].new_val.id` at [Line 286](https://github.com/fuwaneko/loopback-connector-rethinkdb/blob/039e3f5460cf723f55af1873f4ee8f49f03a782e/rethink.js#L286) - However, it's still using default 'id' label instead of my explicit `myId` variable name.

**Comment by fuwaneko** [comment]
Yes, I need to fix handling of custom id names.

**Comment by albhardy** [comment]
Another 'fix' that I did for update attributes in `RethinkDB.prototype.updateAttributes` is to disable `data.id = id;` and insert `get(id)` for 
`r.db(_this.database).table(model).get(id).update(data).run(client, function(err, object) {
        cb(err, data);
    });` 
Otherwise it will add and update all rows with `id` column

**Comment by fuwaneko** [comment]
@albhardy I've added your proposed update and also some additional changes in master. Please, check if it works correctly.

**Comment by albhardy** [comment]
Thanks for the update - So far I found that the latest version do not return the Custom ID from generated RethinkDB id when inserting new object. Under `RethinkDB.prototype.save`, I need to update `idValue = m.changes[0].new_val.id` into 
```
 if (m.inserted > 0) {
                // create
                info.isNewInstance = true
                idValue = m.generated_keys[0]
            }
```
I also need to update `RethinkDB.prototype.all` and change the `filter.where` into
```
if (filter.where) {
        if (filter.where[idName]) {
            var id = filter.where[idName];
            delete filter.where[idName];
            //filter.where.id = id;
        }
        promise = buildWhere(_this, model, filter.where, promise)
        if (promise === null)
            return callback && callback(null, [])
    }
```
Otherwise it will result in Null in when running "Find a model instance by id from the data source" (GET /[Strongloop Model]/{id} )

**Comment by albhardy** [comment]
For the time being, this is the hack that I did:
```
if (filter.where) {
        if (filter.where[idName]) {
            var id = filter.where[idName];
            delete filter.where[idName];
            var f={}
            f[idName]=id;
            promise = buildWhere(_this, model, f, promise)
        }else{
            promise = buildWhere(_this, model, filter.where, promise)
        }
        if (promise === null)
            return callback && callback(null, [])
```
So far, it allows me to find the record with custom ID, but may not work with additional filters
