### ISSUE TITLE
Specify table name

### ISSUE THREAD

**Issue by shader** [fuwaneko/loopback-connector-rethinkdb#13]
How do I specify the table name corresponding to each model? Is there an option I can set in the json file to override the default, which is the same as the model name?

Alternatively, is there a way to override the function that looks up the names? Basically, my table names are the plural of the model name, instead of the singular. If there is a way to use the plural name instead of the singular, that would work too.

**Comment by fuwaneko** [comment]
This is just a connector, please, refer to [official Loopback documentation](https://docs.strongloop.com/display/public/LB/Defining+models) on how to work with models.

**Comment by shader** [comment]
Actually, this is a connector feature. From what I can see in the code, this connector does not implement alternate table names and uses the 'model' name directly.

The mongodb connector has a function that checks first if there is a collection name specified and if so uses it:
```javascript
MongoDB.prototype.collectionName = function(model) {
  var modelClass = this._models[model];
  if (modelClass.settings.mongodb) {
    model = modelClass.settings.mongodb.collection || model;
  }
  return model;
};
```

It would be great if the rethinkdb connector supported something like that, that potentially defaults to the plural name if unspecified (since table names are usually plural).
