### ISSUE TITLE
automigrate doesn't drop tables

### ISSUE THREAD

**Issue by kevintechie** [fuwaneko/loopback-connector-rethinkdb#18]
Is automigrate implemented?

**Comment by Thr1ve** [comment]
It looks like Automigrate currently just calls Autoupdate ( https://github.com/fuwaneko/loopback-connector-rethinkdb/blob/master/rethink.js#L191 ). It does not drop tables.

**Comment by fuwaneko** [comment]
I'll fix all pending issues as soon as I have free time.
