### ISSUE TITLE
Are RethinkDB change-feeds (without polling) in Swift/iOS app possible?

### ISSUE THREAD

**Issue by Rajan** [fuwaneko/loopback-connector-rethinkdb#19]
We are thinking to decide between loopback+rethink and firebase for a new project.
Trying to understand if we can observe the change-feeds in an iOS app without polling or not?
Thank you in advance for your kind response.

**Comment by fuwaneko** [comment]
You will probably need to use RethinkDB directly. Loopback is a classic ORM.
