### ISSUE TITLE
destroyAll missing where in signature

### ISSUE THREAD

**Issue by duffn** [fuwaneko/loopback-connector-rethinkdb#2]
In the current version of LoopBack DELETE /model/{id} calls destroyAll. destroyAll needs to look like
`RethinkDB.prototype.destroyAll = function destroyAll(model, where, callback) {`
and evaluate the where to know which document to delete.

Here's the MongoDB example: https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L633

**Comment by fuwaneko** [comment]
@duffn should be fixed with latest commit

**Comment by duffn** [comment]
Yes, this works now. :+1:
