### ISSUE TITLE
[Loopback 3] The connector rethink does not support replaceById operation

### ISSUE THREAD

**Issue by tylkomat** [fuwaneko/loopback-connector-rethinkdb#25]
The `replaceById` Method was added in Loopback 3 when they changed the behaviour of PUT-Requests to not update attributes any more, but follow the REST specification and replace the model completely.

**Comment by fuwaneko** [comment]
@tylkomat I stopped watching Loopback a while ago and I have no use for this connector anymore. This repo is pretty much unmaintained now, sorry. I'd suggest to look at the forks or you can always make your own fork.

**Comment by tylkomat** [comment]
Thank you for the fast answer.
