### ISSUE TITLE
Can't access included relations' properties

### ISSUE THREAD

**Issue by luisfavila** [fuwaneko/loopback-connector-rethinkdb#26]
Hi! I'm struggling a bit with an include behavior I wouldn't expect.
I have a model A which has a belongsTo relation with model B.

    A.findById(id, {"include":"b"}, function(err, data){
        console.log(data);
        console.log(data.b);
    })

On the first `console.log` I can actually see something like `{ b: { ... }, .... }`, and it's properties but the second one will get me:

    { [Function: bound ]
    getAsync: [Function: bound ],
    update: [Function: bound ],
    destroy: [Function: bound ],
    create: [Function: bound ],
    build: [Function: bound ],
    _targetClass: 'B' }

Then if I try to `console.log(data.b.xproperty)` it will just return undefined when it was clearly shown on the `console.log(data)`

**Comment by fuwaneko** [comment]
@luisfavila I stopped watching Loopback a while ago and I have no use for this connector anymore. This repo is pretty much unmaintained now, sorry. I'd suggest to look at the forks or you can always make your own fork.

**Comment by luisfavila** [comment]
@fuwaneko I just realized I posted on the wrong repo, it was actually meant to be on the loopback repo itself
Thanks!
