### ISSUE TITLE
Driver question

### ISSUE THREAD

**Issue by thaiat** [fuwaneko/loopback-connector-rethinkdb#3]
Hi, i have started using your connector, great work!

I was wondering if you consider it a good idea to switch to using `rethinkdbdash` or `thinky` instead of the standard `rethinkdb` driver.
It would be easier to address pool connection management for example.

Also i was wondering if you have any view on how to integrate with the change feed ?

**Comment by fuwaneko** [comment]
@thaiat thinky is an ORM already. I may look into rethinkdbdash support, it would allow to clean the code a bit. I'm not sure what do you mean by "integrate with the change feed".

**Comment by thaiat** [comment]
@fuwaneko, well i m trying to figure out how to best implement meteor like capabilities...
so the idea would be to expose the crud routes through socket.io (or preferably the new strongloop push feature) and allow a client to register any query to be live through the rethinkdb changefeed

on an angular client u would do something like:
```js
scope.mytable = bindColllection('Customer', 'filterByAge', queryparameter) 
```
and you will get a live mytable array that is recalculated based on changes on the db side

**Comment by fuwaneko** [comment]
@thaiat I'm not sure if Loopback exposes such functionality. This connector is only to allow RethinkDB to be used as a backend for Loopback ORM. Maybe it's possible to extend Loopback Model with "change" event. Also, take a look at this: https://github.com/gritzko/swarm It's similar thing.
