### ISSUE TITLE
use index for orderby by default

### ISSUE THREAD

**Issue by behrad** [fuwaneko/loopback-connector-rethinkdb#4]
normal orderby operation will return ArryaLimit error for large datasets, so in practice and realworld deployments it is crucial to use indexes for them I changed https://github.com/fuwaneko/loopback-connector-rethinkdb/blob/master/rethink.js#L399 to

`promise = promise.orderBy({index:r.desc(key)});`

However we can decide on using indexes based on user configuration of dataSource or even if the same index is available in indexes.

**Comment by fuwaneko** [comment]
Can you make a PR?

**Comment by behrad** [comment]
yup, sure
