### ISSUE TITLE
More powerful  RQL usage

### ISSUE THREAD

**Issue by behrad** [fuwaneko/loopback-connector-rethinkdb#5]
I want to update my docs using

```
    new Model({
      id: id,
      createdAt: 0,
      content: "aaa"
    }).updateAttributes({
        delivered: r.row("delivered").default([]).append( [Date.now(), to] )
    }, function( err, resp ){
        clbk( err );
    });
```

Seems currently I'm not able to pass this, however we can try to enable such queries!?

**Comment by fuwaneko** [comment]
No, we can't. See loopback docs. If you want full RethinkDB driver features, you have to work with it directly.

**Comment by behrad** [comment]
I found that actually the above code is working with this connector :)

**Comment by fuwaneko** [comment]
@behrad then loopback is better than I expected :)

**Comment by behrad** [comment]
loopback knows nothing about this, the data object
```
    {
        delivered: r.row("delivered").default([]).append( [Date.now(), to] )
    }
```
is fully passed to the rethinkDB client, and it does it's job ;) You only should require `r` in your model class.

**Comment by fuwaneko** [comment]
@behrad that's cool, I should probably add this to Readme.
