### ISSUE TITLE
Using a connection pool is hurting performance under high concurrency

### ISSUE THREAD

**Issue by behrad** [fuwaneko/loopback-connector-rethinkdb#6]
Since the nature of node.js connections are non-blocking & async, we don't need a connection pool inside, this will lock the connection for one client until rethinkDB responds.

**Comment by fuwaneko** [comment]
Could you demonstrate perfomance problems under heavy load?

**Comment by behrad** [comment]
I've commented genericPool and using a single connection throughout the connector. this is more responsive. Investigating more on my app now.
If you check node.js client libraries for most of NoSQL dbs like redis, couchbase, ... are using a single connection. 

Node.js idioms are against connection pooling which is traditionally for thread based concurrency.

**Comment by fuwaneko** [comment]
I've never heard anything about "node.js idioms" being against pooling. I even remember article from node.js developer where he implements MySQL pooling to speed up test application. So, until I see performance tests, I'm not convinced.

**Comment by behrad** [comment]
Most of todays NoSQL drivers can preform better operation concurrency or use pipelining which I don't think RDBMS drivers currently can do, so pooling means more critical.

I'm just saying that by `acquire/release` cycle you are serializing concurrent operations on each connection, and that must hurt concurrency. I believe you are better if simply create an array of connections and pass requests round-robin to them. My concern is dropping the `acquire/release` resource locking since a node.js rethinkDB connection should be able to behave multiple operations concurrently in a non-blocking way :)

**Comment by fuwaneko** [comment]
> I believe you are better if simply create an array of connections and pass requests round-robin to them
That's exactly what node-pool does, but also handles advanced features like keep-alive, reconnect, etc.

**Comment by behrad** [comment]
But it locks the connection when your acquire https://github.com/coopernurse/node-pool/blob/master/lib/generic-pool.js#L314

and you are releasing that in your operation callback. 
As I said, this way you are synchronizing operations in each connection (one operation at a time == each operation's callback should be called by RethinkDB until another gets called).
and now consider when you have around multi-thousand operations in-time and a pool of 100 connections :)
